version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/nodejs-pipeline-demo/
hooks:
  ApplicationStop:
    - location: script/application_container_stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: script/application_container_start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: script/application_container_vaidation.sh
      timeout: 60
      runas: ubuntu