version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      #- echo AWS ECR Login
      #- aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - echo List current directoy path and files
      - ls -lrt && pwd
      - echo Install NodeJs Dependencies
      - npm install
      - ls -lrt
  pre_build:
    commands:
      - echo AWS ECR Login
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build start at `date`
      - echo List of files in current directory
      - ls -ltr
      - echo Docker Version
      - docker build -t nodejs-demo:latest .
      - docker tag nodejs-demo:latest ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo:latest
  post_build:
    commands:
      - echo Push image to AWS ECR
      - docker push ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo:latest
      - echo Build completed on `date`
      - echo Permission change for sh file
      - chmod +x script/*.sh
      - cd script && ls -ltr
artifacts:
  files:
    - '**/*'
  packaging:
    - ZIP
